name: Caddy のビルドとプッシュ
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker イメージのタグ'
        required: true
        default: 'latest'
      push:
        description: 'Docker イメージをプッシュするかどうか'
        required: true
        default: 'false'
jobs:
  build-and-push:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.CR_HOST }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Caddy.Dockerfile
          push: ${{ inputs.push }}
          tags: cr.ingen.work/caddy:${{ inputs.tag }}
