name: Misskey のビルドとプッシュ
on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker イメージのタグ'
        required: true
        type: string
        default: 'latest'
      push:
        description: 'Docker イメージをプッシュするかどうか'
        required: true
        type: boolean
        default: 'false'
      misskey-ref:
        description: 'misskeyリポジトリのタグ'
        type: string
        required: true
        default: 'develop'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.CR_HOST }}
          username: ${{ secrets.CR_USERNAME }}
          password: ${{ secrets.CR_PASS }}
      - name: Checkout misskey repo
        uses: actions/checkout@v3
        with:
          repository: misskey-dev/misskey
          path: misskey
          ref: ${{ inputs.misskey-ref }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: misskey
          push: ${{ inputs.push }}
          tags: cr.ingen.work/misskey:${{ inputs.tag }}
